version: '3.8'

services:
  frontend:
    container_name: playoff-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Exposes frontend on http://localhost:5173
    networks:
      - app-network

networks:
  app-network:
    external: true
