services:
  frontend:
    container_name: playoff-frontend
    image: roihass/playoff-frontend:latest
    restart: always
    environment:
        VITE_BASE_URL: "<api-url>"
    ports:
      - "8080:80" # Exposes frontend on http://localhost:5173
    networks:
      - app-network

networks:
  app-network:
    external: true
